language: node_js
node_js:
  - '10.15.3'
install:
  - yarn
script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: ./dist/
  on:
    branch: master